language = "C"
include_guard = "CBINDGEN_BINDINGS_H"

[defines]
"target_os = ios" = "TARGET_OS_IOS"
"target_os = macos" = "TARGET_OS_MACOS"

[parse.expand]
features = ["cbindgen"]
default_features = false
all_features = false